name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Automatic Versioning
        # You may pin to the exact commit or the version.
        # uses: nicupavel/action-files-version-increment@b91169be7b792ee676d078ea6efa96ae0b0efd4f
      uses: nicupavel/action-files-version-increment@v3
      with:
        # The relative path and name of the json file that holds the metadata
        metadata-file: version-metadata.json
        # The amount to add to existing versions 
        version-increment: 0.0.1 # default is 0.01
      
