name: .NET
on:
  create:
    branches: 
      - release/**
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    defaults:
      run: 
        working-directory: ./src
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup Workloads
      working-directory: ./src/KinderEngine.Maui
      run: dotnet workload restore KinderEngine.Maui.csproj
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
